name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo dnf install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo rm -rf /tmp/git-practice
            cd /tmp && git clone https://github.com/PoovithaR/git-practice.git
            sudo cp /tmp/git-practice/index.html /usr/share/nginx/html/
